# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = tile,class:^(Microsoft-edge)$
windowrule = tile,class:^(Brave-browser)$
windowrule = tile,class:^(Chromium)$
windowrule = float,class:^(pavucontrol)$
windowrule = float,class:^(blueman-manager)$
windowrule = float,class:^(nm-connection-editor)$
windowrule = float,class:^(qalculate-gtk)$
