# -----------------------------------------------------
# Hyprpaper Config
# Author: Silas Zhang (2026)
# -----------------------------------------------------

# 壁纸配置
preload  = $HOME/wallpaper/hyprland.jpg
wallpaper = ,$HOME/wallpaper/hyprland.jpg

# 关闭启动飞溅画面
splash = false