# -----------------------------------------------------
# Hyprland Main Config
# Core Config Includes
# Author: Silas Zhang (2026)
# -----------------------------------------------------

# 显示器 / 分辨率 / 刷新率
source = $HOME/.config/hypr/conf/monitor.conf

# 自启动程序
source = $HOME/.config/hypr/conf/autostart.conf

# 光标主题 / 大小
source = $HOME/.config/hypr/conf/cursor.conf

# 全局环境变量
source = $HOME/.config/hypr/conf/environment.conf

# 键盘布局 / 重复速率
source = $HOME/.config/hypr/conf/keyboard.conf

# Pywal 动态色彩方案
source = $HOME/.cache/wal/colors-hyprland.conf

# =============================================
# 窗口 与 外观配置
# =============================================
source = $HOME/.config/hypr/conf/window.conf
source = $HOME/.config/hypr/conf/decoration.conf
source = $HOME/.config/hypr/conf/layout.conf
source = $HOME/.config/hypr/conf/misc.conf

# =============================================
# 按键 / 规则 / 动画
# =============================================
source = $HOME/.config/hypr/conf/keybinding.conf
source = $HOME/.config/hypr/conf/windowrule.conf
source = $HOME/.config/hypr/conf/animation.conf

# =============================================
# 自定义 & HL4W 拓展
# =============================================
source = $HOME/.config/hypr/conf/custom.conf
source = $HOME/.config/hypr/conf/hl4w.conf

# =============================================
# XDG 桌面门户环境支持
# =============================================
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP