# -----------------------------------------------------
# Hypridle Config
# Author: Silas Zhang (2026)
# -----------------------------------------------------

# 全局基础设置
general {
    ignore_dbus_inhibit = false
    # 单例锁定，防止重复启动 hyprlock
    lock_cmd = pidof hyprlock || hyprlock
    # 休眠前自动锁屏
    before_sleep_cmd = loginctl lock-session
    # 唤醒自动点亮屏幕
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 10分钟 → 自动锁屏
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 11分钟 → 关闭屏幕背光
listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 30分钟 → 自动挂起休眠
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}